name: Summit Goals
description: Mountaineering logbook
markdown: kramdown 
exclude: ["scss", "Gemfile","Gemfile.lock", "README.md","config.rb"]
disqus_short_name: "Ryan McKnight"
url: http://www.summitgoals.com
