name: Ryan McKnight
description: Professional site
markdown: kramdown 
exclude: ["scss", "Gemfile","Gemfile.lock", "README.md","config.rb"]
disqus_short_name: "Ryan McKnight"
url: http://www.ryantmcknight.com
